### ISSUE TITLE
Adding the repo to an online Heroku pipeline that uses JAWS_DB

### ISSUE THREAD

**Issue by BogieBogard** [Census-Group-Project/US-Census-Data-Visualization#6]

**Comment by mfort87** [comment]
Heroku Git URL: https://git.heroku.com/desolate-badlands-37211.git

App can be found at: https://desolate-badlands-37211.herokuapp.com/

Added Jaws DB

Added Everyone in the group as collaborators

I will wait to close until I get ok from majority of group.
